export default function reducer(state: any = {

    SAVE: 'Save',
    SET: 'Set',
    IMPORT: 'Import',
    UPDATE: 'Update',
    READ: 'Read',
    SEND: 'Send',
    ADD: 'Add',
    DELETE: 'Delete',
    CLOSE: 'Close',
    ADVANCED: 'Advanced',
    WRITE: 'Write',
    FETCHED: 'READ',
    WROTE: 'WRITE',
    REFRESH: 'Refresh',

    BTN_ADDD2C: 'Add D2C',
    BTN_ADDC2D: 'Add C2D',
    BTN_ADD_METHOD: 'Add Method',
    BTN_ADD_MOCK: 'Add a Mock Sensor',

    BTN_LBL_SERVER: 'IoT Hub Inspector',
    BTN_LBL_REFRESH: 'Refresh the devices',
    BTN_LBL_STARTALL: 'Start all devices',
    BTN_LBL_STOPALL: 'Stop all devices',
    BTN_LBL_EXIMPORT: 'Save to local or Import/Export JSON',
    BTN_LBL_ADDEVICE: 'Add a new device',
    BTN_LBL_C2D: 'Read the last known value for this desired property.',
    BTN_LBL_D2C: 'Update, Send and Save (Mock sensor will override value)',
    BTN_LBL_REMOVE_SENSOR: 'Remove this mock sensor',
    BTN_LBL_METHOD_PARAMS: 'Get latest info for method call',

    BTN_LBL_UPDATE_NAME: 'Update the name of this mock-device',
    BTN_LBL_ADD_D2C: 'Add a new device to cloud property',
    BTN_LBL_ADD_C2D: 'Add a new cloud to device property',
    BTN_LBL_ADD_METHOD: 'Add a new device method',
    BTN_LBL_DEVICE_START: 'Start the runloop for this device. This is required to send and receive data',
    BTN_LBL_DEVICE_STOP: 'Stop the device',
    BTN_LBL_DEVICE_INSPECT: 'IoT Hub Service Client',
    BTN_LBL_DEVICE_DELETE: 'Delete the device (from this app only)',
    BTN_LBL_SELECT_DEVICE: 'Select this device',
    BTN_LBL_GET_DEVICE_LIST: 'Read this Iot Hubs device registry',

    BTN_LBL_PROPERTY_SAVE: 'Save updates to this property',
    BTN_LBL_PROPERTY_DELETE: 'Delete this property',

    FRM_HRD_INSPECT_HUB: 'IoT Hub Service Client',
    FRM_LBL_ADD_DEVICE: 'Add a new mock device',
    FRM_LBL_CONNSTRING_DEVICE: 'Device or IoT Hub Connection String',
    FRM_LBL_CONNSTRING_DEVICE_NAME: 'mock-devices Device name',

    FRM_LBL_IOT_HUB: 'IoT Hub Connection String',
    FRM_LBL_FIELD_NAME: 'Field Name',

    FRM_LBL_DEVICE_SDKIN: 'Device SDK in',
    FRM_LBL_DEVICE_SDKOUT: 'Device SDK out',
    FRM_LBL_LAST_READ_VALUE: 'Value',
    FRM_LBL_AS_STRING: 'As String',
    FRM_LBL_AS_PROPERTY: 'Return Method Name Property (Return Payload must be String)',
    FRM_LBL_VALUE: 'Value',
    FRM_LBL_RUN_LOOP: 'Include in run loop',
    FRM_LBL_SEND_AS_PROPOBJ: 'Send as JSON object',
    FRM_LBL_GET_AS_PROPOBJ: 'Read as JSON object',
    FRM_LBL_TIME_PERIOD: 'Time Period',
    FRM_LBL_VERSION: 'Version',
    FRM_LBL_LIVE_VALUE: 'Reported "Live" Value',
    FRM_LBL_MOCK_SEN_CFG: 'Mock Sensor Configuration',
    FRM_LBL_EXIMPORT_JSON: 'The current set of mock devices. Use this option to share',
    FRM_LBL_EXIMPORT_LCL: 'Save the current set of mock devices',
    FRM_LBL_EXIMPORT_LCL_LOAD: 'Load a saved state',
    FRM_LBL_MESSAGE: 'Message',
    FRM_LBL_STATUS: 'Status',
    FRM_LBL_STATUSCODE: 'Status Code',
    FRM_LBL_GET_DATA: 'Get Last Sent Value',
    
    FRM_LBL_DEVICE_NAME: 'Device Name (mock-devices)',
    FRM_LBL_DEVICE_CLONE: 'Clone Model (mock-devices)',
    FRM_LBL_DEVICE_CONN_STRING: 'Device Connection String',
    FRM_LBL_DEVICE_HUB_CONN_STRING: 'IoT Hub Connection String',
    FRM_LBL_DEVICE_TEMPLATE: 'Device as Template',
    FRM_LBL_DEVICE_IS_TEMPLATE: 'Make device a template (cannot be started)',
    FRM_LBL_DEVICE_CAP_MODEL_URI: 'Capability Model Uri',
    FRM_LBL_DEVICE_ID: 'Device ID',
    FRM_LBL_DEVICE_DPS_SCOPE: 'DPS Scope',
    FRM_LBL_DEVICE_DPS_PAYLOAD: 'DPS Payload',
    FRM_LBL_DEVICE_DPS_SAS: 'SaS Key',
    FRM_LBL_DEVICE_PASTE_CAP: 'Paste the Capability Model here',
    FRM_LBL_DEVICE_PASTE_STATE: 'Paste the State here',

    FRM_LBL_METHOD_NAME: 'Method Name',
    FRM_LBL_RECEIVED_PARAM: 'Received Params',
    FRM_LBL_RETURN_STATUS: 'Return Status',
    FRM_LBL_PAYLOAD: 'Return Payload',

    TEXT_CTRLC_EXPORT: "(CTRL+C to Export - CTRL+V to Import)",
    TEXT_NOCONNSTR: 'No connection string',
    TEXT_DEVICE_LIST: 'Get Device List',
    TEXT_OVERRIDE_MOCK: 'Override Mock value',
    TEXT_SEND_NOW: 'Send Now',
    TEXT_SEND: 'Send',
    TEXT_C2D: 'C2D',
    TEXT_D2C: 'D2C',
    TEXT_D2C_MOCK: 'D2C by Mock Sensor',
    TEXT_D2C_NO_DEVICES: 'No devices found on this Iot Hub',
    TEXT_NODEVICE: 'Please add or select a device',
    TEXT_FULLTWIN: 'Full Twin',
    TEXT_DESIRED: 'Desired Properties (Only)',
    TEXT_DIRTY_PROPERTY: 'Another property is in an unsaved state. Please save before updating another property or refresh to cancel edit',
    TEXT_JSON_TEMPLATE: 'JSON Template for Value',
    TEXT_DISPLAY_VALUE: 'Display Value as JSON',
    TEXT_CLONE_MODEL: 'Clone the model of this device',

    TEXT_TAB_JSON: 'JSON',
    TEXT_TAB_LCL: 'Local Storage',

    PLH_TXT_DEVICENAME: 'device id or name',
    PLH_TXT_STATE_NAME: 'name or description of this session',
    PLH_TXT_ADD_HUB_CONN: 'Use IoT Hub Inspector to get connection string'
}, action: any) {
    return Object.assign({}, state);
}